version: "3"

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8000"
    restart: always
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DEBUG=False
    networks:
      - test-valur

  frontend:
    build:
      context: frontend/
      args:
        - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}
        - NODE_ENV=${NODE_ENV}
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    restart: always
    environment:
      - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - backend
    networks:
      - test-valur

networks:
  test-valur:
    driver: bridge
