version: "3"

services:
  backend:
    build:
      context: backend/ # Use the backend directory
      dockerfile: Dockerfile # Specify Dockerfile if it's named differently

    ports:
      - "3000:3000"
    restart: always
    environment:
      - DEBUG=1
  frontend:
    build:
      context: frontend/ # Use the current directory
      dockerfile: Dockerfile # Specify Dockerfile if it's named differently
    ports:
      - "8080:80" # Map port 8080 on host to port 80 on the container
    environment:
      - NODE_ENV=production # Set environment variable (optional)
    restart: always
    build:
      context: frontend/ # Use the current directory
      dockerfile: Dockerfile # Specify Dockerfile if it's named differently
    ports:
      - "8080:80" # Map port 8080 on host to port 80 on the container
    environment:
      - NODE_ENV=production # Set environment variable (optional)
    restart: always
